# Generated by Django 4.2.15 on 2024-08-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('topic', models.CharField(default=None, max_length=100)),
                ('short_description', models.CharField(default=None, max_length=200)),
                ('long_description', models.CharField(default=None, max_length=300)),
                ('leve', models.CharField(choices=[('E', 'EASY'), ('M', 'MEDIUM'), ('H', 'HARD')], default='E', max_length=1)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.JSONField()),
            ],
        ),
    ]
